title: "Tony Chae"
description: "writings"
url: "https://tonychae01.github.io"
baseurl: "/learning-by-doing"
markdown: kramdown

collections:
  writings:
    output: true
    permalink: /writings/:name/

defaults:
  - scope:
      path: ""          # 모든 경로
      type: writings    # _writings 컬렉션 문서에만 적용
    values:
      layout: default
