title: "Tony Chae"
description: "writings"
url: "https://tonychae01.github.io"   # 사용자 도메인 (뒤에 / 없음)
baseurl: "/learning-by-doing"         # 프로젝트 경로 (앞에 / 붙임)
markdown: kramdown

collections:
  writings:
    output: true
    permalink: /writings/:name/
