permissions:
  contents: write

title: "Tony Chae"
description: "writings"
url: "https://tonychae01.github.io"
baseurl: "/learning-by-doing"
markdown: kramdown

collections:
  writings:
    output: true
    permalink: /writings/:name/
  readings:
    output: true
    permalink: /readings/:name/

defaults:
  - scope:
      path: ""
      type: writings
    values:
      layout: default
  - scope:
      path: ""
      type: readings
    values:
      layout: default
