title: "Tony Chae"
description: "writings"
url: "https://tonychae01.github.io"
baseurl: "/learning-by-doing"
markdown: kramdown
kramdown:
  math_engine: mathjax
buttondown_username: "tonyschae"

collections:
  writings:
    output: true
    permalink: /writings/:name/

defaults:
  - scope:
      path: ""
      type: writings
    values:
      layout: default
