name: Sync Notion to GitHub

on:
  workflow_dispatch:          # 수동 실행 버튼
  schedule:
    - cron: '0 * * * *'       # 매시간

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (pin versions)
        run: npm install @notionhq/client@2.2.13 notion-to-md@3.1.0


      - name: Run sync script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: node scripts/notion-sync.mjs

      - name: Commit & Push
        run: |
          git config user.name "notion-bot"
          git config user.email "notion-bot@example.com"
          git add -A
          git commit -m "Auto-sync from Notion" || echo "No changes"
          git push
